### ISSUE TITLE
Can't include original select option value

### ISSUE THREAD

**Issue by smoggIT** [kvlsrg/jquery-custom-select#12]
Even setting includeValue true, I can't see any value.

**Comment by kvlsrg** [comment]
@smoggIT Please, provide more details.

Also you can check [docs](https://kvlsrg.github.io/jquery-custom-select/#options) to see expected behavior.

**Comment by smoggIT** [comment]
Docs says: 

> includeValue (type: boolean, default: false) Adds chosen value option to dropdown. If enabled also cancels dropdown options rerender.

I added includeValue:true but no value is added to dropdown. Even in docs sample it does not seem to work.

**Comment by kvlsrg** [comment]
Here is example of included value:

![capture](https://user-images.githubusercontent.com/17578344/45290331-02ffae80-b4f8-11e8-96ac-09768969a813.PNG)

That's actually what should be if `includeValue: true`.
