### ISSUE TITLE
ES6 import

### ISSUE THREAD

**Issue by ghost** [kvlsrg/jquery-custom-select#13]
npm i jquery-custom-select --save-dev

somewhere in my srouces

`import 'jquery-custom-select';`

I except that this line will include source code into my bundle, but there is an error:

`ParseError: 'import' and 'export' may appear only with 'sourceType: module'`

**Comment by kvlsrg** [comment]
What bundler are you using?

**Comment by xama** [comment]
Hello, 
I have the same error, any idea to fix this ?

Thank you

**Comment by kvlsrg** [comment]
@xama Please, provide more details. Which bundler? 
E.g. here some info about same error in babelify: https://github.com/babel/babelify/issues/157
