### ISSUE TITLE
babelrc

### ISSUE THREAD

**Issue by sixnames** [kvlsrg/jquery-custom-select#7]
Добрый день, Сергей! Спасибо большое за отличный плагин! Не могли бы вы добавить в gitignore файл .babelrc . Спасибо за понимание! И успехов вам!

**Comment by kvlsrg** [comment]
@6names Спасибо!

Я считаю неправильным добавлять его в gitignore.

Если вы используете babel-loader, то укажите `"babelrc": false`

```
use: {
  loader: 'babel-loader',
  options: {
    babelrc: false
  }
}
```

Либо `--no-babelrc` если CLI.

> Babel will look for a .babelrc in the current directory of the file being transpiled. If one does not exist, it will travel up the directory tree until it finds either a .babelrc, or a package.json with a "babel": {} hash within.

> Use "babelrc": false in options to stop lookup behavior, or provide the --no-babelrc CLI flag.

**Comment by sixnames** [comment]
Я ещё зелёный). Спасибо за подсказку!
