### ISSUE TITLE
Method to destroy/update the custom select

### ISSUE THREAD

**Issue by plasebo** [kvlsrg/jquery-custom-select#8]
Is there any method to destroy/update the custom select. I got a requirement to select an option from the a first select dropdown, and then populate another dropdown based on the option selected previously.

Please help

**Comment by kvlsrg** [comment]
For now there is no any method for this. To reset custom select it's need to trigger click on first option or kill it & init again. But I'm actually going to update version in a few days, so I think it will be helpful to add reset/refresh method.

**Comment by kvlsrg** [comment]
@plasebo I've added reset method in beta version. You can try it:

```
npm i jquery-custom-select@1.5.0-beta
```

To reset custom select use `'reset'` instead of options for already inited custom selects:

```
$('select').customSelect('reset');
```
